version: "3.2"

services:
  web:
    build:
      context: ./quotes-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - quotesnet
    depends_on:
      - api

  api:
    build: ./quotes-api-example
    ports:
      - "8080:8080"
    networks:
      - quotesnet

networks:
  quotesnet:
    driver: bridge
