version: "3.2"

services:
  frontend:
    build: ./quotes-frontend
    ports:
      - 3000:80
    depends_on:
      - api
    environment:
      API_URL: http://api:8080

  api:
    build: ./quotes-api-example
    ports:
      - 8080:8080
